### ISSUE TITLE
What's different of the gevent ?

### ISSUE THREAD

**Issue by dreampuf** [benoitc/offset#9]
I don't know post this in there is ok. But I'm very curious after read [the slides](https://docs.google.com/file/d/0B2gNkR7hgkIRVFgwSWR4Y2JaZHc/edit?hl=en&forcehl=1).

**Comment by benoitc** [comment]
There are actually 4 mains differences compared to gevent:
- not based on an eventloop. It is using its own scheduler.
- instead of placing events in an eventloop to handle blocking operations, operations will still blocks but in an os thread which can at the end make it a little more stable. Also the standard lib is not patched
- no greenlets use, instead it uses python-fibers
- compatible with pypy

Also it has a channel and select like in go. I think it will be more obvious with the coming changes:
- net and IO API 
- multiprocess. It will be possible to use flower on different processes to handle //

Hope I was clear.
